#!/bin/sh
if [[ $(sudo steamos-devmode status) = "disabled" ]]
then
    sudo steamos-devmode enable --no-prompt
fi
sudo pacman -S --needed jre21-openjdk miniupnpc
upnpc -d 25565 tcp
upnpc -r 25565 tcp
java -jar -Xmx4G paper.jar
upnpc -d 25565 tcp
